- name: Initialize the Kubernetes cluster using kubeadm
  run_once: true
  command: kubeadm init --apiserver-advertise-address="100.0.0.10" --apiserver-cert-extra-sans="100.0.0.10"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16
  ignore_errors: yes


- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config

- name: Install calico pod network
  become: false
  command: kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  delegate_to: localhost
  copy:
    content: "{{ join_command.stdout_lines[0] }}"
    dest: "{{ playbook_dir }}/master_join.sh"
